# Generated by Django 5.2.8 on 2025-11-26 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('isbn', models.CharField(max_length=120, unique=True)),
                ('titulo', models.CharField(max_length=500)),
                ('autor', models.CharField(max_length=500)),
                ('editorial', models.CharField(max_length=500)),
                ('anio_publicacion', models.CharField(max_length=500)),
                ('categoria', models.CharField(max_length=500)),
                ('num_paginas', models.IntegerField()),
                ('ubicacion', models.CharField(max_length=500)),
                ('estado', models.CharField(max_length=100)),
                ('copias_disponibles', models.IntegerField()),
            ],
            options={
                'ordering': ('titulo',),
            },
        ),
    ]
